services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Root123!
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql

  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80" 
    depends_on:
      - sqlserver
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=ApiCotasDB;User Id=sa;Password=Root123!;TrustServerCertificate=True;

volumes:
  sqlserverdata:
    