// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dataContext;

#nullable disable

namespace ApiCotas.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250314122536_CreateTables")]
    partial class CreateTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiCotas.Cotas.GrupoEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id");

                    b.Property<string>("CriadorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("criador_id");

                    b.Property<string>("CriadorNome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nome_criador");

                    b.Property<DateTime>("DataCreate")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_create");

                    b.Property<DateTime>("DataUpdate")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_update");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nome");

                    b.Property<int>("NumeroParticipantes")
                        .HasColumnType("int")
                        .HasColumnName("numero_participantes");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("valor_total");

                    b.HasKey("Id");

                    b.HasIndex("CriadorId");

                    b.ToTable("Consorcios");
                });

            modelBuilder.Entity("ApiCotas.Cotas.UserEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_create");

                    b.Property<DateTime>("DataUpdate")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_update");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nome");

                    b.Property<string>("Roles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("roles");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("senha");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CotaEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id");

                    b.Property<string>("ConsorcioId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("consorcioId");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_create");

                    b.Property<DateTime>("DataUpdate")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_update");

                    b.Property<double>("NumeroCota")
                        .HasColumnType("float")
                        .HasColumnName("numeroCota");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("ConsorcioId");

                    b.ToTable("Cotas");
                });

            modelBuilder.Entity("ApiCotas.Cotas.GrupoEntity", b =>
                {
                    b.HasOne("ApiCotas.Cotas.UserEntity", "Criador")
                        .WithMany("GruposCriados")
                        .HasForeignKey("CriadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Criador");
                });

            modelBuilder.Entity("CotaEntity", b =>
                {
                    b.HasOne("ApiCotas.Cotas.GrupoEntity", "Consorcio")
                        .WithMany()
                        .HasForeignKey("ConsorcioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consorcio");
                });

            modelBuilder.Entity("ApiCotas.Cotas.UserEntity", b =>
                {
                    b.Navigation("GruposCriados");
                });
#pragma warning restore 612, 618
        }
    }
}
