// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dataContext;

#nullable disable

namespace ApiCotas.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250305195809_RenameCotaEntity")]
    partial class RenameCotaEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiCotas.Cotas.CotaEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id");

                    b.Property<string>("ConsorcioId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("consorcioId");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_create");

                    b.Property<DateTime>("DataUpdate")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_update");

                    b.Property<double>("NumeroCota")
                        .HasColumnType("float")
                        .HasColumnName("numeroCota");

                    b.Property<int?>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<double?>("Valor")
                        .HasColumnType("float")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.ToTable("Cotas");
                });
#pragma warning restore 612, 618
        }
    }
}
